import { ExternalLink, FileSpreadsheet, RefreshCw, Search, Trash2, Upload } from "lucide-react";
import { useEffect,useMemo,useRef,useState } from "react";
import * as XLSX from "xlsx";
import { clearJiraIssues,loadJiraIssues,replaceJiraSource,type JiraIssue,type JiraSource } from "../services/jira/storage";

type Period={mode:string;days?:number;sprint?:{id:number;name:string;state:string;startDate?:string;endDate?:string;completeDate?:string};reason?:string};
type JiraApiResponse={readOnly?:boolean;count?:number;issues?:JiraIssue[];period?:Period;error?:string};
function notify(){window.dispatchEvent(new Event("jira-issues-updated"));}
function norm(s:string){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");}
function value(row:Record<string,unknown>,aliases:string[]){for(const alias of aliases){const found=Object.entries(row).find(([k])=>norm(k)===norm(alias));if(found&&found[1]!=null)return String(found[1]).trim();}return"";}
function parseRows(rows:Record<string,unknown>[]):JiraIssue[]{return rows.map(row=>({key:value(row,["Issue key","Key","Chave","Chave do item"]),summary:value(row,["Summary","Resumo","Título","Titulo"]),status:value(row,["Status"]),priority:value(row,["Priority","Prioridade"]),assignee:value(row,["Assignee","Responsável","Responsavel"]),description:value(row,["Description","Descrição","Descricao"]),created:value(row,["Created","Criado","Data de criação"]),updated:value(row,["Updated","Atualizado","Data de atualização"]),issueType:value(row,["Issue Type","Tipo de item","Tipo"]),source:"primary" as const})).filter(x=>x.key||x.summary);}
function fmtDate(v?:string){if(!v)return"N/D";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("pt-BR");}
function CardsTable({issues,query}:{issues:JiraIssue[];query:string}){const q=query.toLowerCase().trim();const rows=q?issues.filter(x=>[x.key,x.summary,x.status,x.priority,x.assignee,x.description].some(v=>(v||"").toLowerCase().includes(q))):issues;if(!issues.length)return <div className="rounded-2xl border border-dashed border-line bg-panel p-8 text-center text-sm text-muted"><FileSpreadsheet className="mx-auto mb-2 size-8"/>Nenhum card carregado nesta fonte.</div>;return <div className="overflow-hidden rounded-2xl border border-line bg-panel"><div className="overflow-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-panel-2 text-xs text-muted"><tr><th className="p-3">Chave</th><th className="p-3">Resumo</th><th className="p-3">Status</th><th className="p-3">Prioridade</th><th className="p-3">Responsável</th><th className="p-3">Atualizado</th></tr></thead><tbody>{rows.slice(0,500).map(x=><tr key={(x.source||"primary")+x.key+x.summary} className="border-t border-line"><td className="p-3 font-semibold text-accent">{x.url?<a href={x.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:underline">{x.key}<ExternalLink className="size-3"/></a>:x.key||"N/D"}</td><td className="max-w-xl p-3">{x.summary||"N/D"}</td><td className="p-3">{x.status||"N/D"}</td><td className="p-3">{x.priority||"N/D"}</td><td className="p-3">{x.assignee||"N/D"}</td><td className="p-3">{x.updated||"N/D"}</td></tr>)}</tbody></table></div></div>}
export function JiraPage(){const[issues,setIssues]=useState<JiraIssue[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[info,setInfo]=useState(""),[syncing,setSyncing]=useState<JiraSource|null>(null),[mode,setMode]=useState("days"),[days,setDays]=useState(30),[period,setPeriod]=useState<Period|null>(null);const input=useRef<HTMLInputElement>(null);const refresh=async()=>setIssues(await loadJiraIssues());useEffect(()=>{void refresh().catch(()=>setError("Não foi possível restaurar os cards salvos."));},[]);const primary=useMemo(()=>issues.filter(x=>(x.source??"primary")==="primary"),[issues]);const tools=useMemo(()=>issues.filter(x=>x.source==="tools"),[issues]);
async function sync(source:JiraSource){try{setSyncing(source);setError("");setInfo("");const response=await fetch(source==="tools"?"/api/jira-tools":"/api/jira",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(source==="primary"?{mode,days}:{})});const data=await response.json() as JiraApiResponse;if(!response.ok)throw new Error(data.error||`Falha HTTP ${response.status}`);const synced=(data.issues??[]).map(x=>({...x,source}));await replaceJiraSource(synced,source);await refresh();notify();if(source==="primary")setPeriod(data.period??null);setInfo(`${synced.length.toLocaleString("pt-BR")} cards sincronizados do ${source==="primary"?"Jira principal":"Jira Tools (devs)"}.`);}catch(e){setError(e instanceof Error?e.message:"Falha ao sincronizar Jira.");}finally{setSyncing(null);}}
async function importFile(file:File){try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=wb.Sheets[wb.SheetNames[0]],parsed=parseRows(XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""}));if(!parsed.length)throw new Error("Nenhum card reconhecido.");await replaceJiraSource(parsed,"primary");await refresh();notify();setInfo(`${parsed.length} cards importados para o Jira principal.`);}catch(e){setError(e instanceof Error?e.message:"Falha ao importar.");}finally{if(input.current)input.current.value="";}}
async function remove(source:JiraSource){await clearJiraIssues(source);await refresh();notify();}
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">Cards Jira</h2><p className="mt-1 text-sm text-muted">As duas fontes ficam separadas. O Jira Tools é usado somente como referência para saber se os outros devs já possuem card criado.</p></div><div><input ref={input} className="hidden" type="file" accept=".csv,.xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/><button onClick={()=>input.current?.click()} className="inline-flex items-center gap-2 rounded-xl border border-line bg-panel px-4 py-2.5 text-sm font-semibold"><Upload className="size-4"/>Importar Jira principal</button></div></div>
{error?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}{info?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{info}</div>:null}
<label className="flex items-center gap-2 rounded-xl border border-line bg-panel px-3 py-2"><Search className="size-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nos dois Jiras..." className="w-full bg-transparent text-sm outline-none"/></label>
<section className="space-y-4 rounded-2xl border border-line bg-panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">Jira principal · Dootax</p><p className="mt-1 text-xs text-muted">Fonte principal da nossa triagem e decisões. {primary.length.toLocaleString("pt-BR")} cards carregados.</p></div><button onClick={()=>void remove("primary")} className="inline-flex items-center gap-1 text-xs text-muted"><Trash2 className="size-3.5"/>Limpar</button></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs text-muted">Período<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-1 block rounded-lg border border-line bg-panel px-3 py-2 text-sm"><option value="days">Últimos dias</option><option value="activeSprint">Sprint ativa</option><option value="lastSprint">Última sprint encerrada</option></select></label>{mode==="days"?<label className="text-xs text-muted">Dias<select value={days} onChange={e=>setDays(Number(e.target.value))} className="mt-1 block rounded-lg border border-line bg-panel px-3 py-2 text-sm"><option value={15}>15 dias</option><option value={30}>30 dias</option><option value={45}>45 dias</option><option value={60}>60 dias</option><option value={90}>90 dias</option></select></label>:null}<button onClick={()=>void sync("primary")} disabled={syncing!==null} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw className={`size-4 ${syncing==="primary"?"animate-spin":""}`}/>{syncing==="primary"?"Sincronizando...":"Sincronizar Jira principal"}</button></div>{period?.sprint?<div className="rounded-xl border border-line bg-panel-2 p-3 text-xs text-muted"><strong>{period.sprint.name}</strong> · {fmtDate(period.sprint.startDate)} até {fmtDate(period.sprint.endDate)}</div>:null}<CardsTable issues={primary} query={query}/></section>
<section className="space-y-4 rounded-2xl border border-violet-200 bg-violet-50/40 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="font-semibold">Jira Tools · outros devs</p><span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-bold text-violet-700">SOMENTE REFERÊNCIA</span></div><p className="mt-1 text-xs text-muted">Board 31. Não entra como nossa fila principal; serve para identificar cards que já foram criados pelos outros desenvolvedores. {tools.length.toLocaleString("pt-BR")} cards carregados.</p></div><button onClick={()=>void remove("tools")} className="inline-flex items-center gap-1 text-xs text-muted"><Trash2 className="size-3.5"/>Limpar</button></div><button onClick={()=>void sync("tools")} disabled={syncing!==null} className="inline-flex items-center gap-2 rounded-xl border border-violet-300 bg-white px-4 py-2.5 text-sm font-semibold text-violet-800 disabled:opacity-60"><RefreshCw className={`size-4 ${syncing==="tools"?"animate-spin":""}`}/>{syncing==="tools"?"Sincronizando...":"Sincronizar Jira Tools"}</button><CardsTable issues={tools} query={query}/></section></div>}
